DROP DATABASE IF EXISTS shop;
CREATE DATABASE shop;

CREATE TABLE brands (
    id UUID PRIMARY KEY,
    name VARCHAR UNIQUE NOT NULL
);

CREATE TABLE categories (
    id UUID PRIMARY KEY,
    name VARCHAR UNIQUE NOT NULL
);

