DROP DATABASE IF EXISTS shop;
CREATE DATABASE shop;
\c four_finance;

CREATE TABLE brands (
    id UUID PRIMARY KEY,
    name VARCHAR UNIQUE NOT NULL
);

CREATE TABLE categories (
    id UUID PRIMARY KEY,
    name VARCHAR UNIQUE NOT NULL
);

